# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1131, 715)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Funix-phan-tich-du-doan.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 150, 55, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(360, 90, 481, 491))
        self.widget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.widget.setStyleSheet("background:rgba(208, 208, 160, 1);\n"
"border-radius: 30px\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(170, 80, 261, 91))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("COLOR: ")
        self.label_4.setObjectName("label_4")
        self.lineEdiUsername = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdiUsername.setGeometry(QtCore.QRect(30, 240, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdiUsername.setFont(font)
        self.lineEdiUsername.setStyleSheet("BORDER-RADIUS: 10PX;\n"
"background: rgb(255, 255, 255)")
        self.lineEdiUsername.setText("")
        self.lineEdiUsername.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdiUsername.setObjectName("lineEdiUsername")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEditPassword.setGeometry(QtCore.QRect(30, 320, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setStyleSheet("BORDER-RADIUS: 10PX;\n"
"background: rgb(255, 255, 255)")
        self.lineEditPassword.setText("")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonLogIn = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonLogIn.setGeometry(QtCore.QRect(160, 400, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonLogIn.setFont(font)
        self.pushButtonLogIn.setStyleSheet("QPushButton#pushButtonLogIn{background:rgb(233, 230, 136);color:black;\n"
"border-radius: 10px;}\n"
"QPushButton#pushButtonLogIn:hover{background:rgb(201, 216, 183);}\n"
"QPushButton#pushButtonLogIn:pressed{background:rgb(201, 216, 183) ; color: white; padding-top: 5px}")
        self.pushButtonLogIn.setObjectName("pushButtonLogIn")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(56, 88, 81, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\project\\ICON\\login\\you.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(-280, 0, 1771, 881))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\\project\\ICON\\login\\loginscreen.png"))
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.label_2.raise_()
        self.widget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1131, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; color:#6791a7;\">LOGIN NOW</span></p></body></html>"))
        self.lineEdiUsername.setPlaceholderText(_translate("MainWindow", "    USER NAME"))
        self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "    PASSWORD"))
        self.pushButtonLogIn.setText(_translate("MainWindow", "L o g I n"))
